//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace galaxyGeoloc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hotel
    {
        public int hotelId { get; set; }
        public string hotelName { get; set; }
        public string city { get; set; }
        public string address { get; set; }
        public Nullable<int> zipCode { get; set; }
        public string Price { get; set; }
        public string Discount { get; set; }
        public string roomType { get; set; }
    }
}
