//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace galaxyGeoloc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class logging
    {
        public int logId { get; set; }
        public string discription { get; set; }
        public Nullable<System.DateTime> createdDateTime { get; set; }
        public Nullable<int> userId { get; set; }
    
        public virtual user user { get; set; }
    }
}
